### ISSUE TITLE
Decode uplink data message failure ReferenceError: acc is not defined at decodeUplink (<eval>:155:49(542))

### ISSUE THREAD

**Issue by industrialinternet** [dasdigidings/the_things_stack_v3_tabs_decoder#1]
Thanks for this lib using object tracker on v3 and get this error in the console
Decode uplink data message failure ReferenceError: acc is not defined at decodeUplink (<eval>:155:49(542))

```
  // Accuracy Measurement
  154     positionAccuracy = input.bytes[10] >> 5;
  155      positionAccuracy = Math.pow(2, parseInt(acc) + 2);
```
        
looks like parseInt(acc) and acc isn't defined 
// changed to this error gone but not sure if this correct!!
positionAccuracy = Math.pow(2, parseInt( positionAccuracy) + 2);

**Comment by Drasek** [comment]
You are right!
At first the variable was named acc but i wanted it to be more decribing so i changed it and forgot one instance. Thank you very much for pointing it out! It is fixed now with the new commit. I have no object locator here to test it, i got just a soundlevel, light, presence detection, door & window and humidity sensor to test.
